In [9]:
import pandas as pd

In [10]:
import numpy as np

In [11]:
df=pd.read_csv("C:/Users/chitr/Downloads/crop_yield.csv/crop_yield.csv")

In [12]:
df.head()

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
0,West,Sandy,Cotton,897.077239,27.676966,False,True,Cloudy,122,6.555816
1,South,Clay,Rice,992.673282,18.026142,True,True,Rainy,140,8.527341
2,North,Loam,Barley,147.998025,29.794042,False,False,Sunny,106,1.127443
3,North,Sandy,Soybean,986.866331,16.644190,False,True,Rainy,146,6.517573
4,South,Silt,Wheat,730.379174,31.620687,True,True,Cloudy,110,7.248251

In [13]:
df.tail()

,Region,Soil_Type,Crop,Rainfall_mm,Temperature_Celsius,Fertilizer_Used,Irrigation_Used,Weather_Condition,Days_to_Harvest,Yield_tons_per_hectare
999995,West,Silt,Rice,302.805345,27.987428,False,False,Sunny,76,1.347586
999996,South,Chalky,Barley,932.991383,39.661039,True,False,Rainy,93,7.311594
999997,North,Peaty,Cotton,867.362046,24.370042,True,False,Cloudy,108,5.763182
999998,West,Silt,Wheat,492.812857,33.045505,False,False,Sunny,102,2.070159
999999,West,Sandy,Maize,180.936180,27.298847,True,False,Sunny,76,2.937243

In [14]:
df.isnull().sum()

Region                    0
Soil_Type                 0
Crop                      0
Rainfall_mm               0
Temperature_Celsius       0
Fertilizer_Used           0
Irrigation_Used           0
Weather_Condition         0
Days_to_Harvest           0
Yield_tons_per_hectare    0
dtype: int64

In [15]:
df.dropna(inplace=True)

In [16]:
numeric_df=df.select_dtypes(include="number")

result=pd.DataFrame({
    "dd":numeric_df.mean(),
    "cd":numeric_df.median(),
    "cp":numeric_df.mode().iloc[0]
})
print(result.round(3))

                             dd       cd       cp
Rainfall_mm             549.982  550.124  100.001
Temperature_Celsius      27.505   27.507   15.000
Days_to_Harvest         104.495  104.000   91.000
Yield_tons_per_hectare    4.649    4.652   -1.148

In [17]:
numeric_df=df.select_dtypes(include="number")

result=pd.DataFrame({
    "mean":numeric_df.mean(),
    "median":numeric_df.median(),
    "mode":numeric_df.mode().iloc[0]
})
print(result.round())

                         mean  median   mode
Rainfall_mm             550.0   550.0  100.0
Temperature_Celsius      28.0    28.0   15.0
Days_to_Harvest         104.0   104.0   91.0
Yield_tons_per_hectare    5.0     5.0   -1.0

In [18]:
result1=pd.DataFrame({
    "Variance":numeric_df.var(),
    "Standard Deviation":numeric_df.std()
})
print(result1)

                            Variance  Standard Deviation
Rainfall_mm             67522.708650          259.851320
Temperature_Celsius        52.137174            7.220608
Days_to_Harvest           673.579609           25.953412
Yield_tons_per_hectare      2.878358            1.696572

In [19]:
result2=pd.DataFrame({
    "Minimum":numeric_df.min(),
    "Maximum":numeric_df.max(),
    "Range":numeric_df.max()-numeric_df.min()
})
print(result2.astype(str))

                                   Minimum            Maximum  \
Rainfall_mm             100.00089622522204   999.998098221668
Temperature_Celsius     15.000034141430271  39.99999662316004
Days_to_Harvest                       60.0              149.0
Yield_tons_per_hectare  -1.147613222534901  9.963372228814649

                                     Range
Rainfall_mm              899.9972019964459
Temperature_Celsius     24.999962481729767
Days_to_Harvest                       89.0
Yield_tons_per_hectare   11.11098545134955

In [20]:
result3=pd.DataFrame({
    "Q1 (25%)":numeric_df.quantile(0.25),
    "Q2 (50%)":numeric_df.quantile(0.50),
    "Q3 (75%)":numeric_df.quantile(0.75)
})
result3["IQR"]=result3["Q3 (75%)"]-result3["Q1 (25%)"]
print(result3)

                          Q1 (25%)    Q2 (50%)    Q3 (75%)         IQR
Rainfall_mm             324.891090  550.124061  774.738520  449.847430
Temperature_Celsius      21.254502   27.507365   33.753267   12.498765
Days_to_Harvest          82.000000  104.000000  127.000000   45.000000
Yield_tons_per_hectare    3.417637    4.651808    5.879200    2.461563

In [21]:
result4=pd.DataFrame({
    "skewness":numeric_df.skew()
})

print(result4.round(3))

                        skewness
Rainfall_mm               -0.001
Temperature_Celsius       -0.001
Days_to_Harvest            0.000
Yield_tons_per_hectare    -0.001

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns 
column = numeric_df.columns[0]


sns.histplot(numeric_df[column],kde=True)

plt.title(f"skewness distribution of {column}")
plt.xlabel(column)
plt.ylabel("Frequency")
plt.show()

print("skewness:",numeric_df[column].skew())